#include<iostream>
#include<cassert>
#include<string>
#include"complex.hpp"
using std::cout;
using std::endl;
int main(){ 
    Complex a(1,1), b(2, 2), c(4, 4),tempobj;
    assert(a==a);
    assert(!(a!=a));
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    assert((a==Complex(1,1))&&(b==Complex(2,2))&&(c==Complex(4,4)));
    cout<<"b = c: "<<(b = c)<<endl;
    assert(b==c);
    cout<<"b: "<<b<<" c: "<<c<<endl;
    cout<<"(a=b)=c: "<<((a=b)=c)<<endl;
    assert((a==b)&&(b==c));
    cout<<"a: "<<a<<endl;
    a = {1,1};
    b = {2,2};
    c = {3,3};
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    cout<<"a=b=c"<<(a=b=c)<<endl;
    assert((a==b)&&(b==c));
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    cout<<"a==b: "<<(a==b)<<endl;
    assert(a==b);
    cout<<"a!=b: "<<(a!=b)<<endl;
    assert(!(a!=b));
    a = {1,1};
    b = {1,-1};
    cout<<"a: "<<a<<" b: "<<b<<endl;
    cout<<"a==b: "<<(a==b)<<endl;
    cout<<"a!=b: "<<(a!=b)<<endl;
    b = {0, 1};
    cout<<"b: "<<b<<endl;
    cout<<"a==b: "<<(a==b)<<endl;
    cout<<"a!=b: "<<(a!=b)<<endl;
    cout<<"2 * a: "<<(2 * a)<<endl;
    assert((2 * a)==Complex(2,2));
    cout<<"a * 2: "<<(a * 2)<<endl;
    assert((a * 2)==Complex(2,2));
    cout<<"a + 8: "<<(a + 8)<<endl;
    assert((a + 8)==Complex(9,1));
    cout<<"8 + a: "<<(8 + a)<<endl;
    assert((8 + a)==Complex(9,1));
    cout<<"a / 8: "<<(a/8)<<endl;
    assert((a / 8)==Complex(0.125,0.125));
    cout<<"8 / a: "<<(8/a)<<endl;
    assert((8 / a)==Complex(4,-4));
    tempobj = a;
    cout<<"a += 8: "<< (a+=8)<<endl;
    assert((tempobj+=8)==Complex(9,1));
    cout<<"a: "<<a<<endl;
    cout<<"a -= 8: "<<(a-=8)<<endl;
    assert((tempobj-=8)==Complex(1,1));
    cout<<"a: "<<a<<endl;
    cout<<"b: "<<b<<endl;
    cout<<"a += b: "<<(a+=b)<<endl;
    assert((tempobj+=b)==Complex(1,2));
    cout<<"a: "<<a<<endl;
    cout<<"c: "<<c<<endl;
    cout<<"a = b+= c: "<<(a=b+=c)<<endl;
    assert((c==Complex(3,3))&&(b==Complex(3,4))&&(a==Complex(3,4)));
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    a = {1, 1};
    cout<<"a: "<<a<<endl;
    cout<<"a = b-= c: "<<(a=b-=c)<<endl;
    assert((c==Complex(3,3))&&(b==Complex(0,1))&&(a==Complex(0,1)));
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    cout<<"a + b: "<<(a+b)<<endl;
    assert((a+b)==Complex(0,2));
    cout<<"a - b: "<<(a-b)<<endl;
    assert((a-b)==Complex(0,0));
    cout<<"-b + a: "<<(-b+a)<<endl;
    assert((-b+a)==Complex(0,0));
    cout<<"5 - b + a * 2: "<<(5 - b + a * 2)<<endl;
    assert((5 - b + a * 2)==Complex(5,1));
    cout<<"a: "<<a<<" b: "<<b<<endl;
    cout<<"c = a + b: "<<(c=a+b)<<endl;
    assert(c==Complex(0,2));
    cout<<"c: "<<c<<endl;
    cout<<"c = a - b: "<<(c=a-b)<<endl;
    assert(c==Complex(0,0));
    cout<<"c: "<<c<<endl;
    cout<<"a, b: "<<a<<" "<<b<<endl;
    cout<<"a*b: "<<(a*b)<<endl;
    assert((a*b)==Complex(-1,0));
    cout<<"a/b: "<<(a/b)<<endl;
    assert((a/b)==Complex(1,0));
    a = {1, 1};
    b = {1, -1};
    cout<<"a, b: "<<a<<" "<<b<<endl;
    cout<<"a * b: "<<(a*b)<<endl;
    assert((a*b)==Complex(2,0));
    cout<<"a / b: "<<(a/b)<<endl;
    assert((a/b)==Complex(0,1));
    //unary operations:
    a = {1,1};
    assert((+a)==Complex(1,1));
    assert((-a)==Complex(-1,-1));
    assert((++a)==Complex(2,1));
    assert(a==Complex(2,1));
    assert((a++)==Complex(2,1));
    assert(a==Complex(3,1));
    assert((--a)==Complex(2,1));
    assert(a==Complex(2,1));
    assert((a--)==Complex(2,1));
    assert(a==Complex(1,1));
    assert(static_cast<double>(a)==1.);
}
