#include<iostream>
#include"complex.hpp"
using std::cout;
using std::endl;
int main(){
    Complex a(1,1), b(2, 2), c(4, 4);
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    cout<<"b = c: "<<(b=c)<<endl;
    cout<<"b: "<<b<<" c: "<<c<<endl;
    cout<<"(a=b)=c: "<<((a=b)=c)<<endl;
    cout<<"a: "<<a<<endl;
    a = {1,1};
    b = {2,2};
    c = {3,3};
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    cout<<"a=b=c"<<(a=b=c)<<endl;
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    cout<<"a==b: "<<(a==b)<<endl;
    cout<<"a!=b: "<<(a!=b)<<endl;
    a = {1,1};
    b = {1,-1};
    cout<<"a: "<<a<<" b: "<<b<<endl;
    cout<<"a==b: "<<(a==b)<<endl;
    cout<<"a!=b: "<<(a!=b)<<endl;
    b = {0, 1};
    cout<<"b: "<<b<<endl;
    cout<<"a==b: "<<(a==b)<<endl;
    cout<<"a!=b: "<<(a!=b)<<endl;
    cout<<"2 * a: "<<(2 * a)<<endl;
    cout<<"a * 2: "<<(a * 2)<<endl;
    cout<<"a + 8: "<<(a + 8)<<endl;
    cout<<"8 + a: "<<(8 + a)<<endl;
    cout<<"a / 8: "<<(a/8)<<endl;
    cout<<"8 / a: "<<(8/a)<<endl;
    cout<<"a += 8: "<<(a+=8)<<endl;
    cout<<"a: "<<a<<endl;
    cout<<"a -= 8: "<<(a-=8)<<endl;
    cout<<"a: "<<a<<endl;
    cout<<"b: "<<b<<endl;
    cout<<"a += b: "<<(a+=b)<<endl;
    cout<<"a: "<<a<<endl;
    cout<<"c: "<<c<<endl;
    cout<<"a = b+= c: "<<(a=b+=c)<<endl;
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    a = {1, 1};
    cout<<"a: "<<a<<endl;
    cout<<"a = b-= c: "<<(a=b-=c)<<endl;
    cout<<"a: "<<a<<" b: "<<b<<" c: "<<c<<endl;
    cout<<"a + b: "<<(a+b)<<endl;
    cout<<"a - b: "<<(a-b)<<endl;
    cout<<"-b + a: "<<(-b+a)<<endl;
    cout<<"5 - b + a * 2: "<<(5 - b + a * 2)<<endl;
    cout<<"a: "<<a<<" b: "<<b<<endl;
    cout<<"c = a + b: "<<(c=a+b)<<endl;
    cout<<"c: "<<c<<endl;
    cout<<"c = a - b: "<<(c=a-b)<<endl;
    cout<<"c: "<<c<<endl;
    cout<<"a, b: "<<a<<" "<<b<<endl;
    cout<<"a*b: "<<(a*b)<<endl;
    cout<<"a/b: "<<(a/b)<<endl;
    a = {1, 1};
    b = {1, -1};
    cout<<"a, b: "<<a<<" "<<b<<endl;
    cout<<"a * b: "<<(a*b)<<endl;
    cout<<"a / b: "<<(a/b)<<endl;
    c = {42.55, 532};
    b = {228,0};
    a = {321,9};
}
